server:
  port: 8080
spring:
  datasource:
    initialization-mode: always
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diary
    username: postgres
    password: 654212ll
springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: true